Add eb env

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -1,10 +1,6 @@
 name: Continuous Deployment
 
 on:
-  workflow_run:
-    workflows: ["Continuous Integration"]
-    types: [completed]
-
   workflow_dispatch:
 
 jobs:
@@ -20,12 +16,24 @@ jobs:
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
+          aws-region: ap-southeast-1
 
-      - name: Install Elastic Beanstalk CLI
+      - name: Install EB CLI
         run: |
           pip install --upgrade pip
           pip install awsebcli
 
+      - name: Create EB environment if missing
+        run: |
+          if ! eb list | grep -q drug-classification-env; then
+            echo "EB environment not found. Creating..."
+            eb create drug-classification-env \
+              --platform "Python 3.11" \
+              --single \
+              --timeout 30
+          else
+            echo "EB environment already exists."
+          fi
+
       - name: Deploy to Elastic Beanstalk
-        run: make eb-deploy
+        run: eb deploy
